import { useMemo, useEffect, useState } from 'react';
import { VegaLite } from 'react-vega';

// Import Responsive Chart Specs (Generated by spotify.py)
import defaultSpotify from '../../assets/data/spotify/Charts/Muntakim_Standard.json';
import portraitSpotify from '../../assets/data/spotify/Charts/Muntakim_Portrait.json';
import landscapeSpotify from '../../assets/data/spotify/Charts/Muntakim_Landscape.json';
import tabletPortraitSpotify from '../../assets/data/spotify/Charts/Muntakim_TabletPortrait.json';
import tabletSpotify from '../../assets/data/spotify/Charts/Muntakim_Tablet.json';

import './index.scss';

// --- Helpers ---

/** Pick Vega Spec Based on Viewport (Same Breakpoints as Steam / GoodReads) */
const getSpotifySpec = (width, height) => {
  if (width <= 550 && height >= width) return portraitSpotify; // Phone Portrait
  if (width <= 900 && width > height) return landscapeSpotify; // Phone Landscape
  if (width <= 900) return tabletPortraitSpotify; // iPad Mini / Air / Small Tablet
  if (width <= 1200) return tabletSpotify; // Large Tablet / iPad Pro
  return defaultSpotify; // Desktop
};

const isPortrait = (width, height) => width <= 550 && height >= width;

/**
 * Portrait Spec Embeds Top Songs + Recently Played as Datasets
 * (_cardData Points to Those Dataset Keys). React Renders Them as Cards.
 */
const extractCardData = (spec) => {
  const meta = spec._cardData;
  if (!meta || !spec.datasets) return null;

  const topSongs = (spec.datasets[meta.topSongsDataset] || [])
    .filter((row) => row.song?.trim())
    .sort((a, b) => a.rank - b.rank);

  const recentlyPlayed = (spec.datasets[meta.recentlyPlayedDataset] || [])
    .filter((row) => row.song?.trim())
    .sort((a, b) => a.rank - b.rank);

  if (!topSongs.length && !recentlyPlayed.length) return null;
  return { topSongs, recentlyPlayed };
};

/** Strip Custom Fields Vega Does Not Understand Before Rendering */
const cleanSpec = (spec) => {
  const copy = JSON.parse(JSON.stringify(spec));
  delete copy._cardData;
  return copy;
};

// --- Track Cards (Mobile Portrait Only) ---

const TrackCard = ({ rank, song, artist, time }) => (
  <div className = "spotify-track-card">
    <span className = "spotify-track-rank">{rank}</span>
    <div className = "spotify-track-info">
      <span className = "spotify-track-title">{song}</span>
      {artist && <span className = "spotify-track-artist">{artist}</span>}
    </div>
    {time && <span className = "spotify-track-time">{time}</span>}
  </div>
);

const TrackCardList = ({ title, subtitle, tracks, showTime }) => (
  <div className = "spotify-card-section">
    <h3 className = "spotify-card-section-title">{title}</h3>
    {subtitle && <p className = "spotify-card-section-subtitle">{subtitle}</p>}
    <div className = "spotify-card-list">
      {tracks.map((t, i) => (
        <TrackCard
          key = {`${t.rank}-${t.song}-${i}`}
          rank = {t.rank}
          song = {t.song}
          artist = {t.artist}
          time = {showTime ? t.time : null}
        />
      ))}
    </div>
  </div>
);

// --- Charts ---

const SpotifyCharts = () => {
  const chartsDivStyle = {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  };

  // State for Dimensions
  const [dimensions, setDimensions] = useState({
    width: window.innerWidth,
    height: window.innerHeight,
  });

  // Update Dimensions with Resize Listener
  useEffect(() => {
    const handleResize = () => {
      setDimensions({
        width: window.innerWidth,
        height: window.innerHeight,
      });
    };
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  // Cache Spec to Avoid Unnecessary Re-Renders
  const rawSpec = useMemo(() => {
    return getSpotifySpec(dimensions.width, dimensions.height);
  }, [dimensions]);

  const spec = useMemo(() => cleanSpec(rawSpec), [rawSpec]);

  // Mobile Portrait: Pull Track Lists Out of Spec for Card UI
  const portrait = isPortrait(dimensions.width, dimensions.height);
  const cardData = portrait ? extractCardData(rawSpec) : null;

  return (
    <>
      <div className = "vega-chart" style = {chartsDivStyle}>
        <VegaLite spec = {spec} actions = {false} />
      </div>

      {/* Cards Replace Crowded Vega Tables on Phone Portrait */}
      {portrait && cardData && (
        <div className = "spotify-cards-container">
          {cardData.topSongs.length > 0 && (
            <TrackCardList
              title = "Top Songs"
              subtitle = "Past Year"
              tracks = {cardData.topSongs}
              showTime = {false}
            />
          )}
          {cardData.recentlyPlayed.length > 0 && (
            <TrackCardList
              title = "Recently Played"
              tracks = {cardData.recentlyPlayed}
              showTime = {true}
            />
          )}
        </div>
      )}
    </>
  );
};

const SpotifyDashboard = () => {
  return (
    <div className = "spotify-dashboard">
      <SpotifyCharts />
    </div>
  );
};

export default SpotifyDashboard;
